Repository Kathybui732/viewing_party, pull requests merged in 2020-08, with the labels that each got.

#30 Add feature: Logging in with Google Account
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/welcome_controller.rb
  app/models/user.rb
  app/views/dashboard/index.html.erb
  app/views/layouts/application.html.erb
  app/views/welcome/index.html.erb
  config/initializers/omniauth.rb
  config/routes.rb
  db/migrate/20200819212714_create_users.rb
  db/schema.rb
  spec/features/session/create_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
Labels: enhancement

#35 Add Discover index page
  .travis.yml
  app/controllers/discover_controller.rb
  app/views/dashboard/index.html.erb
  app/views/discover/index.html.erb
  config/routes.rb
  spec/features/discover/index_spec.rb
Labels: enhancement

#41 Add and configure Webmock and VCR gems for testing with mocks and stubs
  .travis.yml
  Gemfile
  Gemfile.lock
  spec/features/discover/find_movies_feature_spec.rb
  spec/features/movies/link_from_discover_spec.rb
  spec/features/movies/movie_result_titles_are_links_spec.rb
  spec/features/movies/top_rated_results_spec.rb
  spec/fixtures/vcr_cassettes/.keep
  spec/fixtures/vcr_cassettes/As_an_authenticated_user/On_Discover_Page/I_can_go_to_movie_index_page_from_the_discover_page.yml
  spec/fixtures/vcr_cassettes/Discover_Movies_Page/As_an_authenticated_user/can_search_for_movies_using_a_keyword.yml
  spec/fixtures/vcr_cassettes/Movie_title_links/As_an_authenticated_user/Movies_index_page/has_links_to_the_movie_s_show_page_from_search_query.yml
  spec/fixtures/vcr_cassettes/Movie_title_links/As_an_authenticated_user/Movies_index_page/has_links_to_the_movie_s_show_page_from_top_rated_query.yml
  spec/fixtures/vcr_cassettes/Top_Rated_Results_Spec/When_I_click_the_button_to_discover_top_rated_movies/There_are_40_results_of_Movies.yml
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: API consumption, new feature, testing

#45 Add friends
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/friendships_controller.rb
  app/controllers/sessions_controller.rb
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/friendship.rb
  app/models/user.rb
  app/views/dashboard/index.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  db/migrate/20200823165146_add_email_to_users.rb
  db/migrate/20200823165606_create_friendships.rb
  db/migrate/20200823191101_change_column_name_user_id_on_users.rb
  db/schema.rb
  spec/features/dashboard/dashboard_links_spec.rb
  spec/features/discover/find_movies_feature_spec.rb
  spec/features/discover/index_spec.rb
  spec/features/friends/add_friends_spec.rb
  spec/features/movies/link_from_discover_spec.rb
  spec/features/movies/movie_result_titles_are_links_spec.rb
  spec/features/movies/top_rated_results_spec.rb
  spec/models/friendship_spec.rb
  spec/models/user_spec.rb
Labels: new feature, testing

#42 Add movie details tests
  .travis.yml
  Gemfile
  Gemfile.lock
  spec/features/discover/find_movies_feature_spec.rb
  spec/features/movies/link_from_discover_spec.rb
  spec/features/movies/movie_result_titles_are_links_spec.rb
  spec/features/movies/show_spec.rb
  spec/features/movies/top_rated_results_spec.rb
  spec/fixtures/vcr_cassettes/.keep
  spec/fixtures/vcr_cassettes/As_an_authenticated_user/On_Discover_Page/I_can_go_to_movie_index_page_from_the_discover_page.yml
  spec/fixtures/vcr_cassettes/Discover_Movies_Page/As_an_authenticated_user/can_search_for_movies_using_a_keyword.yml
  spec/fixtures/vcr_cassettes/Movie_Show_Page/As_an_authenticated_user/I_can_see_movie_details.yml
  spec/fixtures/vcr_cassettes/Movie_title_links/As_an_authenticated_user/Movies_index_page/has_links_to_the_movie_s_show_page_from_search_query.yml
  spec/fixtures/vcr_cassettes/Movie_title_links/As_an_authenticated_user/Movies_index_page/has_links_to_the_movie_s_show_page_from_top_rated_query.yml
  spec/fixtures/vcr_cassettes/Top_Rated_Results_Spec/Each_movie_result_has/the_movie_title_links_to_that_movie_show_page_and_there_is_vote_average.yml
  spec/fixtures/vcr_cassettes/Top_Rated_Results_Spec/When_I_click_the_button_to_discover_top_rated_movies/There_are_40_results_of_Movies.yml
  spec/poros/cast_member_spec.rb
  spec/poros/movie_spec.rb
  spec/poros/review_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: testing

#46 Add feature: Movie details page
  app/controllers/movies_controller.rb
  app/facade/search_results.rb
  app/poro/cast_member.rb
  app/poro/movie.rb
  app/poro/review.rb
  app/services/the_movies_data_base_service.rb
  app/views/movies/show.html.erb
  spec/features/movies/show_spec.rb
  spec/features/movies/top_rated_results_spec.rb
  spec/fixtures/vcr_cassettes/Movie_Show_Page/As_an_authenticated_user/I_can_see_movie_details.yml
  spec/fixtures/vcr_cassettes/Top_Rated_Results_Spec/Each_movie_result_has/the_movie_title_links_to_that_movie_show_page_and_there_is_vote_average.yml
  spec/poros/cast_member_spec.rb
  spec/poros/movie_spec.rb
  spec/poros/review_spec.rb
Labels: new feature

#47 Adds feature: A viewing party can be created for a movie
  Gemfile
  Gemfile.lock
  app/controllers/sessions_controller.rb
  app/controllers/viewing_party_controller.rb
  app/models/party.rb
  app/models/party_invitee.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  app/views/movies/show.html.erb
  app/views/viewing_party/new.html.erb
  config/routes.rb
  db/migrate/20200825200720_add_columns_to_users.rb
  db/migrate/20200825201758_remove_expires_at_from_users.rb
  db/migrate/20200826212156_create_parties.rb
  db/migrate/20200826213302_create_party_invitees.rb
  db/schema.rb
  spec/features/dashboard/dashboard_links_spec.rb
  spec/features/discover/find_movies_feature_spec.rb
  spec/features/discover/index_spec.rb
  spec/features/friends/add_friends_spec.rb
  spec/features/movies/link_from_discover_spec.rb
  spec/features/movies/movie_result_titles_are_links_spec.rb
  spec/features/movies/show_spec.rb
  spec/features/movies/top_rated_results_spec.rb
  spec/features/viewing_party/create_spec.rb
  spec/fixtures/vcr_cassettes/As_an_authenticated_user/On_Discover_Page/I_can_go_to_movie_index_page_from_the_discover_page.yml
  spec/fixtures/vcr_cassettes/Buffy_Show_Page.yml
  spec/fixtures/vcr_cassettes/Create_Viewing_Party_Spec/As_an_authenticated_user/There_is_a_form_to_create_a_viewing_party.yml
  spec/fixtures/vcr_cassettes/Discover_Movies_Page/As_an_authenticated_user/can_search_for_movies_using_a_keyword.yml
  spec/fixtures/vcr_cassettes/Movie_Show_Page/As_an_authenticated_user/I_can_see_movie_details.yml
  spec/fixtures/vcr_cassettes/Movie_title_links/As_an_authenticated_user/Movies_index_page/has_links_to_the_movie_s_show_page_from_search_query.yml
  spec/fixtures/vcr_cassettes/Movie_title_links/As_an_authenticated_user/Movies_index_page/has_links_to_the_movie_s_show_page_from_top_rated_query.yml
  spec/fixtures/vcr_cassettes/New_Viewing_Party_Page.yml
  spec/fixtures/vcr_cassettes/Top_Rated_Results_Spec/Each_movie_result_has/the_movie_title_links_to_that_movie_show_page_and_there_is_vote_average.yml
  spec/fixtures/vcr_cassettes/Top_Rated_Results_Spec/When_I_click_the_button_to_discover_top_rated_movies/There_are_40_results_of_Movies.yml
  spec/models/friendship_spec.rb
  spec/models/party_invitee_spec.rb
  spec/models/party_spec.rb
  spec/models/user_spec.rb
Labels: new feature
